services:
  frontend:
    build: ./frontend
    container_name: frontend-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules

  backend:
    build: ./backend
    container_name: backend-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo_database


  mongo_database:
    image: mongo:noble
    container_name: local-mongodb
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo_sync:
    build: ./backend
    container_name: mongo-sync
    entrypoint: ["sh", "/app/scripts/sync-atlas.sh"]
    env_file:
      - ./backend/.env
    depends_on:
      - mongo_database
    profiles:
      - manual
    
volumes:
  mongo_data:
  mongo_config:
  node_modules_backend:
  node_modules_frontend: